# Generated by Django 4.2.3 on 2023-07-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
